### ISSUE TITLE
2.3.0 blender error when sending job

### ISSUE THREAD

**Issue by ialebedev** [CGRU/cgru.github.com#5]
![screenshot_20181108_161751](https://user-images.githubusercontent.com/16067800/48201909-86ad0e80-e374-11e8-818c-86b9e561484f.png)

Here is the screenshot of an error.
Debian 9 64bit, Blender 2.79b

**Comment by predat** [comment]
Hi @ialebedev,

This is not the correct place to open issue relative to CGRU/Afanasy.
This repo is use for versionning cgru.info web site.

Please open a new issue here: https://github.com/CGRU/cgru/issues

I close this one.
