### ISSUE TITLE
Missing scrollbar

### ISSUE THREAD

**Issue by plaffitt** [CGRU/cgru.github.com#8]
Hello.

First of all, thank you for your awesome work, your tool is the perfect fit for our needs.

I would like to request a small change about the display of the website. I would like to be able to see the scrollbar on the right side of the website when needed (if the content is taller than my screen). I guess that the removal of the scrollbar was a choice of design, but unfortunately, it makes the navigation harder. I like to know where I am on a web page, and I also enjoy to be able to go straight to the top/bottom/anywhere using this scrollbar.

If you agree on this, I can even do it myself and submit a pull-request.

Thanks for your attention!

**Comment by timurhai** [comment]
Hi, Paul.

Sorry for very long delay, but it seems that I occasionally unclicked watch on this repository!

The site was spitted on documentation on https://cgru.readthedocs.io/en/latest/
And on just one page on https://cgru.info/
Where just some project key features specified, and also now I am collecting studio logos and some frames from movies.
You can add yours ))

ps
Now I am watching all events from this repo.
